#!/bin/bash

### BEGIN INIT INFO
# Provides:          audinary
# Required-Start:    $syslog $time $remote_fs
# Required-Stop:     $syslog $time $remote_fs
# X-Start-Before:    kdm gdm3 xdm lightdm
# X-Stop-After:      kdm gdm3 xdm lightdm
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1 6
# Short-Description: audinary daemon
# Description: The purpose of this script is to run the audinary daemon
#	       for the textual time desklet. It runs a server @ http://localhost:3800/
### END INIT INFO

ROOT_PATH=/usr/local/sbin
DAEMON=$ROOT_PATH/audinary
NAME=audinary
PIDFILE=/run/$NAME.pid
DESC="Textual Time Desklet"
SCRIPTNAME=/etc/init.d/audinary

. /lib/lsb/init-functions

case "$1" in
 	  start)	log_daemon_msg "Starting $DESC" "$NAME"
				start-stop-daemon --exec "$DAEMON" --oknodo --start
				log_end_msg $?
				;;
	   stop)	log_daemon_msg "Stopping $DESC" "$NAME"
				start-stop-daemon --signal 9 --exec "$DAEMON" --retry 5 --stop
				log_end_msg $?
				;;
	restart)	log_daemon_msg "Restarting $DESC" "$NAME"
				if start-stop-daemon --signal 9 --exec "$DAEMON" --retry 5 --stop; then
					start-stop-daemon --exec "$DAEMON" --oknodo --start
				fi
				log_daemon_msg $?
				;;
	      *)	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
				exit 1
				;;
esac

exit 0
